name: Test my code

on: push

jobs:
  test:
    name: npm ci
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: npm ci
      uses: docker://node:10-alpine
      with:
        entrypoint: npm
        args: ci

    - name: npm test
      uses: docker://node:10-alpine
      with:
        entrypoint: npm
        args: test
