name: Test my code

on: push

jobs:
  lint:
    name: Test code
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Install deps
      uses: docker://node:10-alpine
      with:
        entrypoint: npm
        args: ci

    - name: Test
      uses: docker://node:10-alpine
      with:
        entrypoint: npm
        args: run test

  test:
    name: Test action against own code
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Install deps
      uses: docker://node:10-alpine
      with:
        entrypoint: npm
        args: ci

    - name: Test
      uses: omgimalexis/ava-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        check_name: Test action against own code
